project:
  type: website
  output-dir: docs

website:
  title: "DS-334 Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://davidzuhlsdorf.github.io/ds334_blog/
        icon: linkedin
        href: www.linkedin.com/in/david-zuhlsdorf-a7a369336

format:
  html:
    theme: superhero
    css: styles.css

editor: visual

